media:
  input: static/images
  output: /images

content:
  - name: creators
    label: Creators
    path: content/creators
    type: collection
    fields:
      - name: name
        label: Name
        type: string
      - name: slug
        label: Slug
        type: string
      - name: discipline
        label: Discipline
        type: string
      - name: tagline
        label: Tagline
        type: string
      - name: bio
        label: Bio
        type: rich-text
      - name: image
        label: Portrait
        type: image
      - name: published
        label: Published
        type: boolean

  - name: projects
    label: Projects
    path: content/projects
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: slug
        label: Slug
        type: string
      - name: category
        label: Category
        type: string
      - name: image
        label: Cover Image
        type: image
      - name: description
        label: Description
        type: rich-text
      - name: creators
        label: Creators (slugs)
        type: string
      - name: published
        label: Published
        type: boolean
